import Foundation
import SpacetimeDB

public typealias BSATNEncoder = SpacetimeDB.BSATNEncoder
public typealias SpacetimeClient = SpacetimeDB.SpacetimeClient
public typealias TableCache<T: Decodable & Sendable> = SpacetimeDB.TableCache<T>

// MARK: - Bundle compat
// Bundle.module is generated by SPM but absent in Xcode app targets.
extension Bundle {
    static var resourceBundle: Bundle {
        #if SWIFT_PACKAGE
        return .module
        #else
        return .main
        #endif
    }
}
